# Generated by Django 2.0.7 on 2018-08-02 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repertoire_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(default='Anonymous', max_length=255)),
                ('priority', models.IntegerField(default=10)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('played', models.BooleanField(default=False)),
                ('currently_playing', models.BooleanField(default=False)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire_manager.PieceModel')),
            ],
        ),
    ]
