# Generated by Django 2.0.7 on 2018-08-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PieceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PROGRESS', 'in progress'), ('REJECTED', 'rejected'), ('DONE', 'done')], default='NEW', max_length=32)),
                ('type', models.CharField(choices=[('MOVIE', 'movie'), ('CLASSICAL', 'classical'), ('ANIME', 'anime'), ('GAME', 'game'), ('TRANSCRIPTION', 'transcription'), ('OTHER', 'other')], default='OTHER', max_length=32)),
                ('number_of_requests', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('movement', models.CharField(blank=True, max_length=32, null=True)),
                ('nick', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
