# Generated by Django 2.0.7 on 2018-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire_manager', '0004_auto_20180812_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecemodel',
            name='s_id',
            field=models.IntegerField(default=-1),
        ),
    ]
