# Generated by Django 2.0.7 on 2018-11-02 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire_manager', '0005_piecemodel_s_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MOVIE', 'movie'), ('CLASSICAL', 'classical'), ('ANIME', 'anime'), ('GAME', 'game'), ('TRANSCRIPTION', 'transcription'), ('OTHER', 'other'), ('HALLOWEEN', 'halloween')], default='OTHER', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='piecemodel',
            name='type',
        ),
        migrations.AddField(
            model_name='piecetags',
            name='piece_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repertoire_manager.PieceModel'),
        ),
    ]
